### ISSUE TITLE
Add CUDAnative and CUDAdrv to REQUIRE?

### ISSUE THREAD

**Issue by jpsamaroo** [Evizero/WaveSimulator.jl#3]
Currently, `WaveSimulator` will not load without `CUDAnative` and `CUDAdrv` being installed. Thankfully, `CUDAnative` and `CUDAdrv` have been designed to load regardless of whether the user's system contains nVidia drivers (I've tested this on my own system while writing tests for `WaveSimulator`).

**Comment by Evizero** [comment]
Maybe. I'll admit I never planned to release the code so I wasn't worried about CI and such.

Ideally we will want it to run such that CI tests the CPU stuff. While offline (if the resources exist) it will run the GPU tests as well. I have not looked into what we would need to make that work

**Comment by jpsamaroo** [comment]
I haven't tried it, but I think the logic near the beginning of PR #4 should automatically turn on CUDA tests when there is a valid driver configured and usable. I've never setup GPU CI before either, but I think it's worth considering. I'll research what's required to set that up!

**Comment by jpsamaroo** [comment]
Closing since #7 added the appropriate packages, and also ensures that CUDA code is only loaded if the CUDA driver is available. Will open a new issue to address CI.
